name: Multi-Architecture Build

on:
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP Version'
        required: true
        default: '8.3'
        type: choice
        options:
          - '8.1'
          - '8.2'
          - '8.3'
      freescout_version:
        description: 'FreeScout Version'
        required: true
        default: '1.8.174'
      push_images:
        description: 'Push images to Docker Hub'
        required: true
        default: false
        type: boolean

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        if: ${{ github.event.inputs.push_images == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/freescout
          tags: |
            type=raw,value=${{ github.event.inputs.php_version }}-alpine
            type=raw,value=latest,enable=${{ github.event.inputs.php_version == '8.3' }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event.inputs.push_images == 'true' }}
          build-args: |
            PHP_VERSION=${{ github.event.inputs.php_version }}
            FREESCOUT_VERSION=${{ github.event.inputs.freescout_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max